#!/usr/bin/env node
/**
 * The benchmark runner.
 *
 *   tsx bench/audit/cli.ts fixtures --out <dir>
 *   tsx bench/audit/cli.ts gold --out <file.json>
 *   tsx bench/audit/cli.ts score <answers.json> [--fixtures <dir>] [--out <report.md>] [--json <score.json>]
 *
 * `fixtures` writes the tree an arm is allowed to read: the synthetic sessions,
 * a manifest, and one prompt per question wording. The gold answers are written
 * only by `gold`, into a separate path, so an arm's working directory can hold
 * the sessions without holding the answer key.
 *
 * `score` is the whole grader. It compares an arm's answers JSON against the
 * gold by exact match, with no model in the loop, and it rebuilds the fixture
 * bytes itself: a `--fixtures` directory is accepted only when every file in it
 * matches the generated bytes, so an arm cannot be scored against a tree it
 * edited.
 */

import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { loadCitationIndex } from './citations.js'
import { generateBench, writeFixtures, type GeneratedBench } from './fixtures.js'
import { promptRows } from './questions.js'
import { parseAnswersFile, renderArmScore, scoreArm } from './score.js'

const USAGE = [
  'Usage:',
  '  bench/audit/cli.ts fixtures --out <dir>',
  '  bench/audit/cli.ts gold --out <file.json>',
  '  bench/audit/cli.ts score <answers.json> [--fixtures <dir>] [--out <report.md>] [--json <score.json>]',
].join('\n')

interface Args {
  positional: string[]
  flags: Map<string, string>
}

function parseArgs(argv: readonly string[]): Args {
  const positional: string[] = []
  const flags = new Map<string, string>()
  for (let index = 0; index < argv.length; index += 1) {
    const item = argv[index]!
    if (!item.startsWith('--')) {
      positional.push(item)
      continue
    }
    const equals = item.indexOf('=')
    if (equals > 0) {
      flags.set(item.slice(2, equals), item.slice(equals + 1))
      continue
    }
    const value = argv[index + 1]
    if (value === undefined || value.startsWith('--')) throw new Error(`${item} needs a value`)
    flags.set(item.slice(2), value)
    index += 1
  }
  return { positional, flags }
}

async function writeOut(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, content)
}

/** Write the fixture tree plus the manifest and prompts an arm needs. */
async function writeArmInputs(root: string, bench: GeneratedBench): Promise<void> {
  await writeFixtures(root, bench)
  await writeOut(join(root, 'manifest.json'), `${JSON.stringify(bench.manifest, null, 2)}\n`)
  const prompts = promptRows(bench.manifest).map((row) => JSON.stringify(row)).join('\n')
  await writeOut(join(root, 'prompts.jsonl'), `${prompts}\n`)
}

/**
 * A fixture directory is usable only when it still holds the generated bytes.
 * Scoring an arm against a tree the arm could have rewritten would grade the
 * tree, not the arm.
 */
async function assertUnmodified(root: string, bench: GeneratedBench): Promise<void> {
  for (const file of bench.files) {
    const path = join(root, file.path)
    const actual = await readFile(path, 'utf8').catch(() => undefined)
    if (actual === undefined) throw new Error(`fixture directory is missing ${file.path}`)
    if (actual !== file.content) throw new Error(`fixture file differs from the generated bytes: ${file.path}`)
  }
}

async function main(argv: readonly string[]): Promise<number> {
  const [command, ...rest] = argv
  if (!command || command === '--help' || command === '-h') {
    console.log(USAGE)
    return command ? 0 : 1
  }
  const { positional, flags } = parseArgs(rest)
  const bench = generateBench()

  if (command === 'fixtures') {
    const out = flags.get('out')
    if (!out) throw new Error('fixtures needs --out <dir>')
    await writeArmInputs(out, bench)
    console.log(`wrote ${bench.files.length} session files, manifest.json and prompts.jsonl to ${out}`)
    return 0
  }

  if (command === 'gold') {
    const out = flags.get('out')
    if (!out) throw new Error('gold needs --out <file.json>')
    await writeOut(out, `${JSON.stringify(bench.gold, null, 2)}\n`)
    console.log(`wrote gold answers for ${Object.keys(bench.gold).length} questions to ${out}`)
    return 0
  }

  if (command === 'score') {
    const answersPath = positional[0]
    if (!answersPath) throw new Error('score needs an answers JSON path')
    const file = parseAnswersFile(JSON.parse(await readFile(answersPath, 'utf8')) as unknown)
    let root = flags.get('fixtures')
    if (root) await assertUnmodified(root, bench)
    else {
      root = await mkdtemp(join(tmpdir(), 'traces-bench-audit-'))
      await writeFixtures(root, bench)
    }
    const index = await loadCitationIndex(root, bench.manifest)
    const score = scoreArm(file, bench.gold, index)
    const report = renderArmScore(score)
    const out = flags.get('out')
    if (out) await writeOut(out, report)
    else console.log(report)
    const json = flags.get('json')
    if (json) await writeOut(json, `${JSON.stringify(score, null, 2)}\n`)
    return 0
  }

  throw new Error(`unknown command ${command}\n${USAGE}`)
}

main(process.argv.slice(2)).then(
  (code) => {
    process.exitCode = code
  },
  (error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error))
    process.exitCode = 1
  },
)
